services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  db:
    image: docker.arvancloud.ir/postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: docker.arvancloud.ir/redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: docker.arvancloud.ir/nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./link-shortener-frontend/dist:/usr/share/nginx/html
      - ./link-shortener-frontend/dist:/usr/share/nginx/html/pages
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./link-shortener-frontend/dist/locales:/usr/share/nginx/html/locales
      - ./link-shortener-frontend/dist/fonts:/usr/share/nginx/html/fonts
      
    networks:
      - 1sl_default
      - mailcowdockerized_mailcow-network
    depends_on:
      - app
  
volumes:
  postgres_data:

networks:
  1sl_default:
    external: true

  mailcowdockerized_mailcow-network:
    external: true