"""Add click_events table

Revision ID: 73c8593a5fbb
Revises: deba56d0eff1
Create Date: 2025-09-05 14:03:23.158178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c8593a5fbb'
down_revision: Union[str, Sequence[str], None] = 'deba56d0eff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_link_id'), 'click_events', ['link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_events_link_id'), table_name='click_events')
    op.drop_table('click_events')
    # ### end Alembic commands ###
